School/Controllers/ClassesController.cs
using Microsoft.AspNetCore.Mvc;
using School.BL.DTO;
using School.BL.Service;
using School.DL.Repositry;

namespace School.Controllers
{
    public class ClassesController : Controller
    {
        private readonly IClassService _classService;
        private readonly IMaterialRepositry _materialRepositry;
        public ClassesController(IClassService classService,IMaterialRepositry materialRepositry)
        {
            _classService = classService;
            _materialRepositry = materialRepositry;
        }
        public async Task<IActionResult> Index()
        {
            var classes = await _classService.GetAllClasses();
            return View(classes.AsEnumerable());
        }
        public IActionResult AddClass() {
            var model = new ClassDTO
            {
                MateriaLItems = _materialRepositry.GetMaterials().Select(MaterialItem => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = MaterialItem.MaterialNameAr,
                    Value = MaterialItem.Id.ToString()
                }).ToList()
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddClass(ClassDTO input)
        {

            try
            {
                input.MateriaLItems = _materialRepositry.GetMaterials().Select(MaterialItem => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = MaterialItem.MaterialNameAr,
                    Value = MaterialItem.Id.ToString()
                }).ToList();
                if (!String.IsNullOrEmpty(input.ClassNameAr))
                {
                    await _classService.AddClass(input);
                    return RedirectToAction(nameof(Index));
                }
                return View(input);
                
            }
            catch(Exception ex)
            {
               
                ViewBag.ErrorMessage = ex.Message;
                return View(input);

            }
        }
        public async Task<IActionResult> EditClass(int id)
        {
            var cl=await _classService.GetClassById(id);
            cl.MateriaLItems = _materialRepositry.GetMaterials().Select(MaterialItem => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = MaterialItem.MaterialNameAr,
                Value = MaterialItem.Id.ToString()
            }).ToList();
            return View(cl);
        }
        [HttpPost]
        public async Task<IActionResult> EditClass(ClassDTO input)
        {
            try
            {
                input.MateriaLItems = _materialRepositry.GetMaterials().Select(MaterialItem => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = MaterialItem.MaterialNameAr,
                    Value = MaterialItem.Id.ToString()
                }).ToList();
                if (!string.IsNullOrEmpty(input.ClassNameAr))
                {
                    await _classService.UpdateClass(input);
                    return RedirectToAction(nameof(Index));
                }
                return View(input);
            }
            catch (Exception ex)
            {
                
                ViewBag.ErrorMessage = ex.Message;
                return View(input);

            }
        }
        public void Delete(int id)
        {
            _classService.DeleteClassById(id);
        }
    }

}

School/Controllers/LogInController.cs
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal;
using Microsoft.AspNetCore.Mvc;
using School.BL.DTO;
using School.BL.Enum;
using School.BL.Service;
using System.Reflection.Metadata.Ecma335;

namespace School.Controllers
{
    public class LogInController : Controller
    {
        private readonly IUserService _userService;
        private readonly ILoginService _loginService;
        public LogInController(IUserService userService,ILoginService loginService)
        {
           _userService = userService;
           _loginService = loginService;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO login) 
        {
            try
            {
                if (await _loginService.AuthenticateUser(login.Email, login.Password))
                {
                    int? usertype = (int?)(_loginService.GetUserTypeFromSession());
                    if (usertype.HasValue)
                        switch ((UserType)(usertype))
                        {
                            case UserType.Admin:
                                return RedirectToAction("Index", "Material");
                            case UserType.Teacher:
                                return RedirectToAction("Index", "TeacherClass");
                            case UserType.Student:
                                return RedirectToAction("Index", "MarksStudent");
                        }
                }
                ViewBag.ErrorMessage = "The Email or Password Incorrect";
                return View(login);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(login);
            }
        }
        public async Task<IActionResult> Logout()
        {
            _loginService.Logout();
            return RedirectToAction("Index", "Home");
        }  
    }
}

School/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.Protocol.Plugins;
using School.BL.DTO;
using School.BL.Service;
using School.DL.Repositry;

namespace School.Controllers
{
    public class StudentController : Controller
    {
        private readonly IClassService _classService;
        private readonly IStudentService _studentService;
        public StudentController(IClassService classService,IStudentService studentService)
        {
            _classService = classService;
            _studentService = studentService;
        }
        public async Task<IActionResult> Index()
        {
            var students =await _studentService.GetAllStudent();
            return View(students);
        }
        public async Task<IActionResult> RegisterStudent()
        {
            var model = new RegisterStudentDTO();
            model.ClassItems = await GetClassesSelectListItems();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> RegisterStudent(RegisterStudentDTO student)
        {
            try
            {
                await _studentService.RegisterStudent(student);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                student.ClassItems = await GetClassesSelectListItems();
                ViewBag.ErrorMessage = ex.Message;
                return View(student);
            }
        }
        public async Task<IActionResult> EditStudent(int id)
        {
            var student =await _studentService.GetStudent(id);
            student.ClassItems = await GetClassesSelectListItems();
            return View(student);
        }
        [HttpPost]
        public async Task<IActionResult> EditStudent(RegisterStudentDTO student)
        {
            try
            {
                await _studentService.EditStudent(student);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                student.ClassItems = await GetClassesSelectListItems();
                ViewBag.ErrorMessage = ex.Message;
                return View(student);
            }
        }
        public async Task Delete(int id)
        {
            await _studentService.DeleteStudent(id);
        }
        #region Private Method
        private async Task<List<SelectListItem>> GetClassesSelectListItems()
        {
            var classes = await _classService.GetAllClasses();
            return classes.Select(classItem => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = classItem.ClassNameAr,
                Value = classItem.Id.ToString()
            }).ToList();
        }
        #endregion
    }
}

School/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.BL.DTO;
using School.BL.Service;
using School.Core.Entities;
using School.DL.Repositry;

namespace School.Controllers
{
    public class TeacherController : Controller
    {
        private readonly IMaterialService _materialService;
        private readonly ITeacherService _teacherService;
        private readonly IUserService _userService;
        public TeacherController(IMaterialService materialService,ITeacherService teacherService,IUserService userService)
        {
            _materialService = materialService; 
            _teacherService=teacherService;
            _userService = userService;

        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var teachers = await _teacherService.GetAllTeacher();
                return View(teachers);
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View();  
            }
        }
       
        public async Task<IActionResult> AddTeacher() {
            var model = new RegisterTeacherDTO();
            model.MaterialsItems =await GetSelectListMaterialsItems();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddTeacher(RegisterTeacherDTO teacher)
        {
            try
            {
                await _teacherService.AddTeacher(teacher);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                teacher.MaterialsItems = await GetSelectListMaterialsItems();
                ViewBag.ErrorMessage = ex.Message;
                return View(teacher);
            }
        }
        public async Task<IActionResult> EditTeacher(int id)
        {
            var teacher = await _teacherService.GetTeacher(id);
            var materials = await _materialService.GetAllMaterials();
            teacher.MaterialsItems = await GetSelectListMaterialsItems(); 
            return View(teacher);
        }
        [HttpPost]
        public async Task<IActionResult> EditTeacher(RegisterTeacherDTO teacher)
        {
            try
            {
                await _teacherService.EditTeacher(teacher);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                var materials = await _materialService.GetAllMaterials();
                teacher.MaterialsItems = await GetSelectListMaterialsItems();
                ViewBag.ErrorMessage = ex.Message;
                return View(teacher);
            }
        }
        public  async Task Delete(int id)
        {
            try
            {
                await _teacherService.DeleteTeacher(id);
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

        }
        #region Private Method
        private async Task<List<SelectListItem>> GetSelectListMaterialsItems()
        {
            var materials = await _materialService.GetAllMaterials();
            return materials.Select(MaterialItem => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = MaterialItem.MaterialNameAr,
                Value = MaterialItem.Id.ToString()
            }).ToList();
        }
        #endregion
    }
}

School/Views/Shared/_AdminLayout.cshtml
@inject IHttpContextAccessor _httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href="~/admin-panel/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/template/img/logo.png" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <title>Admin Dashboard</title>
</head>

<body>
    <div class="d-flex" id="wrapper">
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
                <i class="fas fa-user-secret me-2"></i>EduSite
            </div>
            <div class="list-group list-group-flush my-3">
                <a asp-action="Index" asp-controller="Material" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <i class="fas fa-book"></i>Materials
                </a>
                <a asp-action="Index" asp-controller="Classes" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <i class="fas fa-chalkboard"></i>Classes
                </a>
                <a  asp-controller="Student" asp-action="Index" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <i class="fas fa-user-graduate me-2"></i>Students
                </a>
                <a asp-action="Index" asp-controller="Teacher" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <i class="fas fa-chalkboard-teacher me-2"></i>Teachers
                </a>
                <a asp-action="Index" asp-controller="User" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <i class="fas fa-user"></i>Users
                </a>
                @if ((bool)_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue)
                {
                    @if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue))
                    {
                        <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" asp-controller="User"
                           asp-action="ResetPassword" asp-route-userId="@_httpContextAccessor.HttpContext?.Session.GetInt32("UserId")">
                            <i class="fas fa-key" style="color:orangered;"></i>Reset Password
                        </a>
                    }
                    <a asp-action="Logout" asp-controller="LogIn" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                        <i class="fas fa-sign-out-alt" style="color: red;"></i>Logout

                    </a>
                }

            </div>
        </div>

                    @RenderBody()
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
</body>

</html>

School/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor _httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Education</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/template/img/logo.png" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EduSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue) &&
                        (bool)((int)_httpContextAccessor.HttpContext?.Session.GetInt32("UserType") == (int)(UserType.Student)))
                        {
                            <li class="nav-item"><a class="nav-link text-dark" asp-controller="MarksStudent" asp-action="Index">Marks</a></li>

                        }
                        @{
                         else if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue) &&
                             (bool)((int)_httpContextAccessor.HttpContext?.Session.GetInt32("UserType") == (int)(UserType.Teacher)))
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-controller="TeacherClass" asp-action="Index">Classes</a></li>

                            }

                        }
                        @if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue))
                        {
                            <li class="nav-item"><a class="nav-link text-dark" asp-controller="User" asp-action="SelfResetPassword">Reset Password</a></li>

                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Blog">Blogs</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>

                        <li>
                        @if ((bool)_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue)
                        {
                                <a asp-action="Logout" asp-controller="LogIn" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                                <i class="fas fa-sign-out-alt" style="color: red;"></i>Logout
                            </a>
                        }
                        else
                        {
                            <a asp-action="Login" asp-controller="LogIn" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                                <i class="fas fa-sign-out-alt" style="color: red;"></i>Login
                            </a>
                        }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

School/Views/Shared/_Schoollayout.cshtml
@inject IHttpContextAccessor _httpContextAccessor
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	    <link rel="shortcut icon" type="image/x-icon" href="~/template/img/logo.png" />
		<title>Education</title>
		<!-- Google font -->
	   <link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">
	   <link href="~/template/css/bootstrap.min.css" rel="stylesheet" />
       <link href="~/template/css/font-awesome.min.css" rel="stylesheet" />
       <link href="~/template/css/style.css" rel="stylesheet" />
    </head>
	<body>

		<!-- Header -->
		<header id="header" class="transparent-nav">
			<div class="container">

				<div class="navbar-header">
					<!-- Logo -->
					<div class="navbar-brand">
						<a class="logo" asp-action="Index" asp-controller="Home">
						<img src="~/template/img/logo-alt.png" alt="logo">
						</a>
					</div>
					<!-- /Logo -->

					<!-- Mobile toggle -->
					<button class="navbar-toggle">
						<span></span>
					</button>
					<!-- /Mobile toggle -->
				</div>

				<!-- Navigation -->
				<nav id="nav">
					<ul class="main-menu nav navbar-nav navbar-right">
						<li><a asp-controller="Home" asp-action="Index">Home</a></li>
					@{
				     if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue)&&
										(bool)((int)_httpContextAccessor.HttpContext?.Session.GetInt32("UserType") == (int)(UserType.Student)))
					 {
						<li><a asp-controller="MarksStudent" asp-action="Index">Marks</a></li>
										
					 }
					 else if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue) &&
						 (bool)((int)_httpContextAccessor.HttpContext?.Session.GetInt32("UserType") == (int)(UserType.Teacher)))
					 {
							<li ><a asp-controller="TeacherClass" asp-action="Index">Classes</a></li>

					 }
					}
					<li><a asp-controller="Home" asp-action="Blog">Blog</a></li>
						<li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
					@if ((bool)_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue)
					{
						<li><a asp-action="Logout" asp-controller="LogIn">Logout</a></li>

					}
					else
					{
						<li><a asp-action="Login" asp-controller="LogIn">LogIn</a></li>

					}
					@if ((bool)(_httpContextAccessor.HttpContext?.Session.GetInt32("UserId").HasValue))
					{
						<li ><a  asp-controller="User" asp-action="SelfResetPassword">Reset Password</a></li>

					}
				</ul>
				</nav>
				<!-- /Navigation -->

			</div>
		</header>
	<div id="home" class="hero-area">

		<!-- Backgound Image -->
		<div class="bg-image bg-parallax bg-home-image overlay" style="background-image: url('../../wwwroot/template/img/home-background.jpg');"></div>
		<!-- /Backgound Image -->

		<div class="home-wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-8">
						<h1 class="white-text">Edusite Free Online Training Courses</h1>
						<p class="lead white-text">Libris vivendo eloquentiam ex ius, nec id splendide abhorreant, eu pro alii error homero.</p>
						<a class="main-button icon-button" href="#">Get Started!</a>
					</div>
				</div>
			</div>
		</div>

	</div>
		<!-- /Header -->
		@RenderBody()
		<!-- Footer -->
		<footer id="footer" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- footer logo -->
					<div class="col-md-6">
						<div class="footer-logo">
							<a class="logo" href="index.html">
							<img src="~/template/img/logo.png" alt="logo">
							</a>
						</div>
					</div>
					<!-- footer logo -->

					<!-- footer nav -->
					<div class="col-md-6">
						<ul class="footer-nav">
							<li><a href="index.html">Home</a></li>
							<li><a href="#">About</a></li>
							<li><a href="#">Courses</a></li>
							<li><a href="blog.html">Blog</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
					<!-- /footer nav -->

				</div>
				<!-- /row -->

				<!-- row -->
				<div id="bottom-footer" class="row">

					<!-- social -->
					<div class="col-md-4 col-md-push-8">
						<ul class="footer-social">
							<li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
							<li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<!-- /social -->

					<!-- copyright -->
					<div class="col-md-8 col-md-pull-4">
						<div class="footer-copyright">
						</div>
					</div>
					<!-- /copyright -->

				</div>
				<!-- row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- preloader -->
		<div id='preloader'><div class='preloader'></div></div>
		<!-- /preloader -->


		<!-- jQuery Plugins -->
    <script src="~/template/js/bootstrap.min.js"></script>
    <script src="~/template/js/jquery.min.js"></script>
    <script src="~/template/js/main.js"></script>
	</body>
</html>